version: '3.2'
services:

  app:
    build:
      context: ./UserBlogApp
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    ports:
      - "8040:80"
      - "44340:443"
    depends_on:
      sqlServer:
        condition: service_healthy
      seq:
        condition: service_started

  sqlServer:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sqlServer
    restart: unless-stopped
    mem_limit: 5g
    memswap_limit: 5g
    volumes:
      - sqlserverdata:/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
    ports:
      - "1433:1433"
    healthcheck:
      test: [
        "CMD", "/opt/mssql-tools/bin/sqlcmd", 
        "-U", "sa", 
        "-P", "${MSSQL_PASSWORD}", 
        "-Q", "SELECT \"READY\""]
      interval: 15s
      retries: 120

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    mem_limit: 5g
    memswap_limit: 5g
    volumes:
      - seqdata:/data
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8020:80
      - 5341:5341

volumes:
  sqlserverdata:
    driver: local
  seqdata:
    driver: local